#TODO change name
server:
  port: ${APP_SERVER_PORT:8080}
#  servlet:
#    context-path: /api

spring:
#  mvc:
#    servlet:
#      path: /api
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

springdoc:
  api-docs:
    resolve-schema-properties: true
  writer-with-order-by-keys: true

management:
  tracing:
    baggage:
      correlation:
        fields:
          - x-amzn-trace-id
      remote-fields:
        - x-amzn-trace-id

logging:
  level:
    it.pagopa.pdv.user_registry: ${APP_LOG_LEVEL:DEBUG}

