#TODO change name
server:
  port: ${MS_USER_REGISTRY_SERVER_PORT:8080}
#  servlet:
#    context-path: /api

spring:
#  mvc:
#    servlet:
#      path: /api
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

logging:
  level:
    it.pagopa.pdv.user_registry: ${MS_USER_REGISTRY_LOG_LEVEL:DEBUG}
