name: integration-tests
description: "Run integration tests"

inputs:
  api_key:
    description: "API Key to perform integration tests"
    required: true
  host_name:
    description: "Host name to perform integration tests"
    required: true
  test_existing_token:
    description: "Existing token for the given API Key"
    required: true
  test_not_existing_token:
    description: "Not existing token for the given API Key"
    required: true
  test_not_allowed_token:
    description: "Not allowed token for the given API Key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run local k6 test
      #grafana/k6-action@0.3.0
      uses: grafana/k6-action@2bd221c807b7cdbe4bb3abc6b3fa4d2da499fa9b
      env:
        API_KEY: ${{ inputs.api_key }}
        HOST_NAME: ${{ inputs.host_name }}
        TEST_EXISTING_TOKEN: ${{ inputs.test_existing_token }}
        TEST_NOT_EXISTING_TOKEN: ${{ inputs.test_not_existing_token }}
        TEST_NOT_ALLOWED_TOKEN: ${{ inputs.test_not_allowed_token }}
      with:
        filename: integration-tests/integration.js

    - name: Manage exit code
      shell: bash
      run: |
        var=$(jq -r ".failed" tmp.json) ; exit $var