name: "Integration-Tests"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: choice
        required: true
        default: dev
        options:
        - dev
        - uat
        - prod

permissions:
  contents: read

jobs:
  k6-integration-tests-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch'}}
    name: integration-tests
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        #actions/checkout@3.2.0
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Integration tests
        uses: ./.github/workflows/integration-tests
        with:
          api_key: ${{ secrets.API_KEY }}
          host_name: ${{ vars.HOST_NAME }}
          test_existing_token: ${{ secrets.TEST_EXISTING_TOKEN }}
          test_not_existing_token: ${{ secrets.TEST_NOT_EXISTING_TOKEN }}
          test_not_allowed_token: ${{ secrets.TEST_NOT_ALLOWED_TOKEN }}